### PR TITLE
answers for lesson 1

### PR DESCRIPTION
**Pull request by Abdulaiman**
done with week one assignment.

### CODE REVIEW

**Review by taylor-knapp — APPROVED** [review]
Great job! 📖 

Random nitpick - it will be easier for me to review in future weeks if you include the numeric prefix on the file names, i.e. `01-intro.js`. ✅ 

Feel free to DM me on slack if you ever have any questions!

**Comment by taylor-knapp** [comment]
Oh - one more thing, it looks like you've submitted a PR against the CTD git repository instead of to your cloned version of the repository. Try to follow [the instructs here](https://learn.codethedream.org/ctd-node-express-class-lesson-1a-node-introduction/) to clone, and let me know if you need some help!

**Comment by Abdulaiman** [comment]
Thanks for your time.
   But i don't understand what you mean by making a pull request against my
cloned version.

And also, am i to make another pull request?

Thanks.

**Comment by taylor-knapp** [comment]
Hi Rabiu. 👋 

You can 'fork' a github repository by clicking the 'Fork' button in the top right:

image

It creates a copy of the repository under your github user. You want to use that copy to submit PRs against.

**Pull request closed without merging**
