### PR TITLE
answers for lesson 1

### PR DESCRIPTION
**Pull request by ElenaCherpakova**

### CODE REVIEW

**Review by jdevries3133 — COMMENTED** [review]
This all looks good! I noticed you committed some .DS_Store files from your Mac. We should try to avoid committing these files; they are generated automatically by finder on macOS. 

You can tell git to ignore a file by adding it to your `.gitignore` file, which is a file that travels with your code repository as it moves between machines. You can also put an entry into a file at `.git/info/exclude` in your repo folder. This hidden file is like a private gitignore file. It only exists on your machine, so it can be ideal for these files. I usually put `/*.md` into this file so that I can create markdown files for noted at the base of my repos and git just ignores those. 

Changing these ignore files doesn't cause git to forget about files it's already tracking, though. To tell git to forget about a previously included file, you need to run `git rm --cached <path-to-file>`, and then make a commit.

**Comment by jdevries3133** [comment]
Also, I forgot to check approve, but I approve! You may merge this and move on to week 2

**Comment by jdevries3133** [comment]
Also, Elena, you'll notice that this pull requests is "targeting" the code the dream repository, not your own. If you go back to the page to create a pull request and look carefully at the drop-downs at the top, you can change the target repository from this one to your own.

We want the pull request to be from the week1 branch of _your own repo_ to the main branch of _your own repo_. That way, when the review is over, you can click the "merge" button, and GitHub will merge your changes for you.

**Comment by ElenaCherpakova** [comment]
Hi Jack, thank you for taking the time to review my code. Fixed it based on your notes.)

**Comment by jrmcgarvey** [comment]
Directed to wrong repository.

**Pull request closed without merging**
