### PR TITLE
doc: week 1 reviewer notes

### PR DESCRIPTION
**Pull request by jdevries3133**
I think some notes for assignment reviewers would provide value; here are my week 1 notes!

### CODE REVIEW

**Review by akosasante — COMMENTED** [review]
This is super helpful Jack! Especially the tip about copying the files and doing a `git diff`. I've been individually comparing with just regular `diff` one-by-one , which has been a bit tedious :facepalm: :facepalm:

**Comment by akosasante** [comment]
One thing that wasn't clear to me when reviewing; is do the students do anything with the `1-event-loop-examples` and the `2-async-patterns` directories?

**Comment by akosasante** [comment]
One thing that came up for me a bunch during the first couple weeks was giving the students tips for how to set up their `.gitignore` and how to format their code in VsCode (with/without `Prettier`). Wonder if there's an appropriate are to include info about that (or if it already exists and I'm just missing where to point folks to :smile: )

**Comment by jdevries3133** [comment]
Yeah, I saw some `.DS_Store` files in a students' work, so I agree the `.gitignore` leaves a bit to be desired. Maybe you can coach that student to make a PR into this repo and we can get the correct `.gitignore` here and also have that student make a proper OSS contribution – 2 birds in 1 stone.

For more miscellaneous docs, I'm not sure.

**Comment by jdevries3133** [comment]
> One thing that wasn't clear to me when reviewing; is do the students do anything with the `1-event-loop-examples` and the `2-async-patterns` directories?

Good point; I see no mention of it in https://learn.codethedream.org/ctd-node-express-class-lesson-1a-node-introduction/ or https://learn.codethedream.org/ctd-node-express-class-lesson-2a-npm-and-async-patterns/.

I've added a note about that.

**Comment by jdevries3133** [comment]
Closing; prefer https://github.com/Code-the-Dream-School/school-pages/pull/25

**Pull request closed without merging**
